/**
 * @file gpio_pins.h
 * 
 * @author Tomasz Watorowski (tomasz.watorowski@gmail.com)
 * @date 2021-06-12
 * 
 * @brief Signal locations definitions done with gpio.h (Arduino)
 */

#ifndef DEV_GPIO_SIGNALS_BLACKPILL_H
#define DEV_GPIO_SIGNALS_BLACKPILL_H


/** @name BlackPill connector signal locations */
/** @{ */
/* ports for 'A' signals */
#define GPIO_SIGNAL_BLACKPILL_A0_PORT                     GPIOA
#define GPIO_SIGNAL_BLACKPILL_A1_PORT                     GPIOA
#define GPIO_SIGNAL_BLACKPILL_A2_PORT                     GPIOA
#define GPIO_SIGNAL_BLACKPILL_A3_PORT                     GPIOA
#define GPIO_SIGNAL_BLACKPILL_A4_PORT                     GPIOA
#define GPIO_SIGNAL_BLACKPILL_A5_PORT                     GPIOA
#define GPIO_SIGNAL_BLACKPILL_A6_PORT                     GPIOA
#define GPIO_SIGNAL_BLACKPILL_A7_PORT                     GPIOA
#define GPIO_SIGNAL_BLACKPILL_A8_PORT                     GPIOA
#define GPIO_SIGNAL_BLACKPILL_A9_PORT                     GPIOA
#define GPIO_SIGNAL_BLACKPILL_A10_PORT                    GPIOA
#define GPIO_SIGNAL_BLACKPILL_A11_PORT                    GPIOA
#define GPIO_SIGNAL_BLACKPILL_A12_PORT                    GPIOA
#define GPIO_SIGNAL_BLACKPILL_A13_PORT                    GPIOA
#define GPIO_SIGNAL_BLACKPILL_A14_PORT                    GPIOA
#define GPIO_SIGNAL_BLACKPILL_A15_PORT                    GPIOA

/* ports for 'B' signals */
#define GPIO_SIGNAL_BLACKPILL_B0_PORT                     GPIOB
#define GPIO_SIGNAL_BLACKPILL_B1_PORT                     GPIOB
#define GPIO_SIGNAL_BLACKPILL_B2_PORT                     GPIOB
#define GPIO_SIGNAL_BLACKPILL_B3_PORT                     GPIOB
#define GPIO_SIGNAL_BLACKPILL_B4_PORT                     GPIOB
#define GPIO_SIGNAL_BLACKPILL_B5_PORT                     GPIOB
#define GPIO_SIGNAL_BLACKPILL_B6_PORT                     GPIOB
#define GPIO_SIGNAL_BLACKPILL_B7_PORT                     GPIOB
#define GPIO_SIGNAL_BLACKPILL_B8_PORT                     GPIOB
#define GPIO_SIGNAL_BLACKPILL_B9_PORT                     GPIOB
#define GPIO_SIGNAL_BLACKPILL_B10_PORT                    GPIOB
#define GPIO_SIGNAL_BLACKPILL_B11_PORT                    GPIOB
#define GPIO_SIGNAL_BLACKPILL_B12_PORT                    GPIOB
#define GPIO_SIGNAL_BLACKPILL_B13_PORT                    GPIOB
#define GPIO_SIGNAL_BLACKPILL_B14_PORT                    GPIOB
#define GPIO_SIGNAL_BLACKPILL_B15_PORT                    GPIOB

/* ports for 'C' signals */
#define GPIO_SIGNAL_BLACKPILL_C13_PORT                    GPIOC
#define GPIO_SIGNAL_BLACKPILL_C14_PORT                    GPIOC
#define GPIO_SIGNAL_BLACKPILL_C15_PORT                    GPIOC

/* pins for 'A' signals */
#define GPIO_SIGNAL_BLACKPILL_A0_PIN                     GPIO_PIN_0
#define GPIO_SIGNAL_BLACKPILL_A1_PIN                     GPIO_PIN_1
#define GPIO_SIGNAL_BLACKPILL_A2_PIN                     GPIO_PIN_2
#define GPIO_SIGNAL_BLACKPILL_A3_PIN                     GPIO_PIN_3
#define GPIO_SIGNAL_BLACKPILL_A4_PIN                     GPIO_PIN_4
#define GPIO_SIGNAL_BLACKPILL_A5_PIN                     GPIO_PIN_5
#define GPIO_SIGNAL_BLACKPILL_A6_PIN                     GPIO_PIN_6
#define GPIO_SIGNAL_BLACKPILL_A7_PIN                     GPIO_PIN_7
#define GPIO_SIGNAL_BLACKPILL_A8_PIN                     GPIO_PIN_8
#define GPIO_SIGNAL_BLACKPILL_A9_PIN                     GPIO_PIN_9
#define GPIO_SIGNAL_BLACKPILL_A10_PIN                    GPIO_PIN_10
#define GPIO_SIGNAL_BLACKPILL_A11_PIN                    GPIO_PIN_11
#define GPIO_SIGNAL_BLACKPILL_A12_PIN                    GPIO_PIN_12
#define GPIO_SIGNAL_BLACKPILL_A13_PIN                    GPIO_PIN_13
#define GPIO_SIGNAL_BLACKPILL_A14_PIN                    GPIO_PIN_14
#define GPIO_SIGNAL_BLACKPILL_A15_PIN                    GPIO_PIN_15

/* pins for 'B' signals */
#define GPIO_SIGNAL_BLACKPILL_B0_PIN                     GPIO_PIN_0
#define GPIO_SIGNAL_BLACKPILL_B1_PIN                     GPIO_PIN_1
#define GPIO_SIGNAL_BLACKPILL_B2_PIN                     GPIO_PIN_2
#define GPIO_SIGNAL_BLACKPILL_B3_PIN                     GPIO_PIN_3
#define GPIO_SIGNAL_BLACKPILL_B4_PIN                     GPIO_PIN_4
#define GPIO_SIGNAL_BLACKPILL_B5_PIN                     GPIO_PIN_5
#define GPIO_SIGNAL_BLACKPILL_B6_PIN                     GPIO_PIN_6
#define GPIO_SIGNAL_BLACKPILL_B7_PIN                     GPIO_PIN_7
#define GPIO_SIGNAL_BLACKPILL_B8_PIN                     GPIO_PIN_8
#define GPIO_SIGNAL_BLACKPILL_B9_PIN                     GPIO_PIN_9
#define GPIO_SIGNAL_BLACKPILL_B10_PIN                    GPIO_PIN_10
#define GPIO_SIGNAL_BLACKPILL_B11_PIN                    GPIO_PIN_11
#define GPIO_SIGNAL_BLACKPILL_B12_PIN                    GPIO_PIN_12
#define GPIO_SIGNAL_BLACKPILL_B13_PIN                    GPIO_PIN_13
#define GPIO_SIGNAL_BLACKPILL_B14_PIN                    GPIO_PIN_14
#define GPIO_SIGNAL_BLACKPILL_B15_PIN                    GPIO_PIN_15

/* pins for 'C' signals */
#define GPIO_SIGNAL_BLACKPILL_C13_PIN                    GPIO_PIN_13
#define GPIO_SIGNAL_BLACKPILL_C14_PIN                    GPIO_PIN_14
#define GPIO_SIGNAL_BLACKPILL_C15_PIN                    GPIO_PIN_15


/* port A signals */
#define GPIO_SIGNAL_BLACKPILL_A0                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A0_PORT, GPIO_SIGNAL_BLACKPILL_A0_PIN)
#define GPIO_SIGNAL_BLACKPILL_A1                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A1_PORT, GPIO_SIGNAL_BLACKPILL_A1_PIN)
#define GPIO_SIGNAL_BLACKPILL_A2                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A2_PORT, GPIO_SIGNAL_BLACKPILL_A2_PIN)
#define GPIO_SIGNAL_BLACKPILL_A3                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A3_PORT, GPIO_SIGNAL_BLACKPILL_A3_PIN)
#define GPIO_SIGNAL_BLACKPILL_A4                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A4_PORT, GPIO_SIGNAL_BLACKPILL_A4_PIN)
#define GPIO_SIGNAL_BLACKPILL_A5                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A5_PORT, GPIO_SIGNAL_BLACKPILL_A5_PIN)
#define GPIO_SIGNAL_BLACKPILL_A6                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A6_PORT, GPIO_SIGNAL_BLACKPILL_A6_PIN)
#define GPIO_SIGNAL_BLACKPILL_A7                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A7_PORT, GPIO_SIGNAL_BLACKPILL_A7_PIN)
#define GPIO_SIGNAL_BLACKPILL_A8                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A8_PORT, GPIO_SIGNAL_BLACKPILL_A8_PIN)
#define GPIO_SIGNAL_BLACKPILL_A9                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A9_PORT, GPIO_SIGNAL_BLACKPILL_A9_PIN)
#define GPIO_SIGNAL_BLACKPILL_A10                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A10_PORT, GPIO_SIGNAL_BLACKPILL_A10_PIN)
#define GPIO_SIGNAL_BLACKPILL_A11                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A11_PORT, GPIO_SIGNAL_BLACKPILL_A11_PIN)
#define GPIO_SIGNAL_BLACKPILL_A12                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A12_PORT, GPIO_SIGNAL_BLACKPILL_A12_PIN)
#define GPIO_SIGNAL_BLACKPILL_A13                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A13_PORT, GPIO_SIGNAL_BLACKPILL_A13_PIN)
#define GPIO_SIGNAL_BLACKPILL_A14                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A14_PORT, GPIO_SIGNAL_BLACKPILL_A14_PIN)
#define GPIO_SIGNAL_BLACKPILL_A15                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_A15_PORT, GPIO_SIGNAL_BLACKPILL_A15_PIN)


/* port B signals */
#define GPIO_SIGNAL_BLACKPILL_B0                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B0_PORT, GPIO_SIGNAL_BLACKPILL_B0_PIN)
#define GPIO_SIGNAL_BLACKPILL_B1                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B1_PORT, GPIO_SIGNAL_BLACKPILL_B1_PIN)
#define GPIO_SIGNAL_BLACKPILL_B2                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B2_PORT, GPIO_SIGNAL_BLACKPILL_B2_PIN)
#define GPIO_SIGNAL_BLACKPILL_B3                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B3_PORT, GPIO_SIGNAL_BLACKPILL_B3_PIN)
#define GPIO_SIGNAL_BLACKPILL_B4                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B4_PORT, GPIO_SIGNAL_BLACKPILL_B4_PIN)
#define GPIO_SIGNAL_BLACKPILL_B5                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B5_PORT, GPIO_SIGNAL_BLACKPILL_B5_PIN)
#define GPIO_SIGNAL_BLACKPILL_B6                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B6_PORT, GPIO_SIGNAL_BLACKPILL_B6_PIN)
#define GPIO_SIGNAL_BLACKPILL_B7                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B7_PORT, GPIO_SIGNAL_BLACKPILL_B7_PIN)
#define GPIO_SIGNAL_BLACKPILL_B8                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B8_PORT, GPIO_SIGNAL_BLACKPILL_B8_PIN)
#define GPIO_SIGNAL_BLACKPILL_B9                          \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B9_PORT, GPIO_SIGNAL_BLACKPILL_B9_PIN)
#define GPIO_SIGNAL_BLACKPILL_B10                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B10_PORT, GPIO_SIGNAL_BLACKPILL_B10_PIN)
#define GPIO_SIGNAL_BLACKPILL_B11                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B11_PORT, GPIO_SIGNAL_BLACKPILL_B11_PIN)
#define GPIO_SIGNAL_BLACKPILL_B12                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B12_PORT, GPIO_SIGNAL_BLACKPILL_B12_PIN)
#define GPIO_SIGNAL_BLACKPILL_B13                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B13_PORT, GPIO_SIGNAL_BLACKPILL_B13_PIN)
#define GPIO_SIGNAL_BLACKPILL_B14                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B14_PORT, GPIO_SIGNAL_BLACKPILL_B14_PIN)
#define GPIO_SIGNAL_BLACKPILL_B15                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_B15_PORT, GPIO_SIGNAL_BLACKPILL_B15_PIN)


/* port C signals*/
#define GPIO_SIGNAL_BLACKPILL_C13                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_C13_PORT, GPIO_SIGNAL_BLACKPILL_C13_PIN)
#define GPIO_SIGNAL_BLACKPILL_C14                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_C14_PORT, GPIO_SIGNAL_BLACKPILL_C14_PIN)
#define GPIO_SIGNAL_BLACKPILL_C15                         \
    GPIO_SIGNAL(GPIO_SIGNAL_BLACKPILL_C15_PORT, GPIO_SIGNAL_BLACKPILL_C15_PIN)

/** @} */

#endif /* DEV_GPIO_SIGNALS_BLACKPILL_H */
